### ISSUE TITLE
Can't install legate.core with CUDA

### ISSUE THREAD

**Issue by BS-astronomer** [nv-legate/legate.core#123]
I tried to install legate.core with CUDA in workstations with gaming GPUs (RTX 3090 and GTX1080) and did not succeed. I am getting errors like:

Already on 'control_replication'
/home/beka/opt/legate.core/legion/runtime/mathtypes/complex.h(126): error: more than one conversion function from "__half" to a built-in type applies:
            function "__half::operator float() const"
/usr/local/cuda//include/cuda_fp16.hpp(204): here
            function "__half::operator short() const"

I suspect these are due to the wrong GPU architecture is given to the compiler.
When I indicate --arch pascal, arch=sm_60 appears in the compiler options.

For my GPUs I need arch=sm_61 or arch=sm_86
How can I get it right?

**Comment by BS-astronomer** [comment]
I have managed to get the correct arch=sm_61 or sm_86, but the problem is not resolved yet.
I cannot understand why do I have such problems.

**Comment by manopapad** [comment]
Could you please share the build command you are using, and the full output from the build? Also your OS and CUDA toolkit version?

**Comment by BS-astronomer** [comment]
Thank you very much for your quick response.

I am working on Ubuntu 20.04.3 LTS (Focal Fossa) 64-bit
Kernel Linux 5.4.0-91-generic x86_64
CUDA 11.5

I am using setup.py and install.py as they are shown in the getting started.
./setup.py --intall-dir /home/beka/opt/legate
./install.py --cuda --with-cuda /usr/local/cuda/ --arch pascal

To change sm_60 to sm_61 I have edited legate.core/legion/runtime/runtime.mk file.
I simply substituted 60 to 61 in line 589
standard and error outputs are here:
[out.txt](https://github.com/nv-legate/legate.core/files/7743335/out.txt)
[err.txt](https://github.com/nv-legate/legate.core/files/7743337/err.txt)
.

**Comment by manopapad** [comment]
Thanks for the output. It looks like `nvcc` is not picking up the `__half` (half-precision floating point) datatype from the CUDA runtime libraries when compiling `legion_redop.cu`. Possibly the specific GPU model does not have native half precision support? I will need to dig into this a little more, but possibly @lightsighter has an idea?

> To change sm_60 to sm_61 I have edited legate.core/legion/runtime/runtime.mk file.

I think `--arch 61` would have also worked.

**Comment by manopapad** [comment]
This was an issue with Legion erroneously disabling some half-precision operator implementations under CUDA 11.5. I have a fix https://gitlab.com/StanfordLegion/legion/-/merge_requests/422 waiting to pass CI. Assuming it completes, @lightsighter will need to merge it into the `control_replication` branch that Legate uses. @BS-astronomer if you'd like to test this immediately, please apply the associated [patch](https://gitlab.com/StanfordLegion/legion/-/merge_requests/422/diffs) onto `/home/beka/opt/legate.core/legion/runtime/mathtypes/half.h` and try building legate.core again.

**Comment by BS-astronomer** [comment]
@manopapad Thank you very much! The solution worked. 

legate seems working now. But I am facing another error:

File "test_001.py", line 1, in <module>
    import legate.numpy as np
ModuleNotFoundError: No module named 'legate.numpy'

Should I install this package separately? Or am I missing something?

**Comment by manopapad** [comment]
You will need to install [cunumeric](https://github.com/nv-legate/cunumeric) (legate.numpy was recently renamed to cunumeric), and change the import statement to `import cunumeric`.

And make sure you use the legate launcher `<legate-install-dir>/bin/legate` to run your script.

**Comment by BS-astronomer** [comment]
Thank you very much for your help! Your work is very much appreciated!
